server:
  servlet:
    context-path: /auth
  port: 8081

eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true

 
spring: 
  application: 
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false
  datasource:
    password: postgres@123
    url: jdbc:postgresql://localhost:5432/mapanet2
    username: postgres
 
jwt:
  config:
    type: signed
    
email:
  naoCadastrado: E-mail não cadastrado. Verifique novamente ou crie um usuário.
  validacao: Confirmação de Email do usuário
  novasenha: Nova senha